#!/usr/bin/env python3
"""
Generate a Markdown API compatibility report between the InquirerPrompt fork
and the upstream kazhala/InquirerPy package from PyPI.

Uses `griffe check` CLI (supports `pypi:` notation) for breaking-change detection,
and the griffe Python API for API surface summary of the local fork.

Usage:
    python scripts/compat_check.py [--output docs/pages/compat_report.md]

Requires:
    pip install griffe[pypi]
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

try:
    import griffe
except ImportError:
    print("ERROR: griffe not installed. Run: pip install griffe[pypi]", file=sys.stderr)
    sys.exit(1)


UPSTREAM_PACKAGE = "InquirerPy"
UPSTREAM_VERSION = "0.3.4"
FORK_SOURCE_PATH = Path(__file__).parent.parent  # repo root
OUTPUT_DEFAULT = Path(__file__).parent.parent / "docs" / "pages" / "compat_report.md"


def run_griffe_check() -> tuple[int, str]:
    """Run `griffe check InquirerPy --against pypi:InquirerPy:0.3.4` and return (returncode, output)."""
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "griffe",
            "check",
            UPSTREAM_PACKAGE,
            "--against",
            f"pypi:{UPSTREAM_PACKAGE}:{UPSTREAM_VERSION}",
            "--search",
            str(FORK_SOURCE_PATH),
            "--verbose",
        ],
        capture_output=True,
        text=True,
    )
    combined = (result.stdout + result.stderr).strip()
    return result.returncode, combined


def load_fork_api() -> griffe.Package | None:
    """Load InquirerPy from the current fork source tree."""
    try:
        return griffe.load(UPSTREAM_PACKAGE, search_paths=[str(FORK_SOURCE_PATH)])
    except Exception as e:
        print(f"WARNING: Could not load fork API: {e}", file=sys.stderr)
        return None


def summarise_package(pkg: griffe.Package) -> dict[str, int]:
    """Return top-level member counts by kind."""
    counts: dict[str, int] = {"Classes": 0, "Functions": 0, "Attributes": 0}
    for obj in pkg.members.values():
        if isinstance(obj, griffe.Class):
            counts["Classes"] += 1
        elif isinstance(obj, griffe.Function):
            counts["Functions"] += 1
        else:
            counts["Attributes"] += 1
    return counts


def generate_report(returncode: int, griffe_output: str, fork: griffe.Package | None) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    has_breakages = returncode != 0 and griffe_output.strip()

    lines: list[str] = [
        f"<!-- AUTO-GENERATED by scripts/compat_check.py on {now} — do not edit manually -->",
        "",
        f"*Report generated: {now}*",
        f"*Upstream reference: `{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}` (PyPI) — Fork: local `master`*",
        "",
    ]

    if not has_breakages:
        lines += [
            "## ✅ No Breaking Changes Detected",
            "",
            f"The public API of this fork is **fully compatible** with upstream "
            f"`{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}`.",
            "All existing code using the upstream package will continue to work without modification.",
            "",
        ]
    else:
        lines += [
            "## ⚠️ API Differences Found",
            "",
            f"The following differences were detected relative to upstream `{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}`.",
            "",
            "```text",
        ]
        lines.append(griffe_output)
        lines += ["```", ""]

    # API surface of fork
    if fork is not None:
        counts = summarise_package(fork)
        lines += [
            "## Fork API Surface (Top-Level)",
            "",
            f"Package: `{UPSTREAM_PACKAGE}` (import name, unchanged from upstream)",
            "",
            "| Kind | Count |",
            "|------|-------|",
        ]
        for kind, n in counts.items():
            lines.append(f"| {kind} | {n} |")
        lines += ["", "---", ""]

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API compatibility report")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_DEFAULT,
        help="Output markdown file path",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with code 1 if breaking changes are found",
    )
    args = parser.parse_args()

    print(f"Running griffe check against pypi:{UPSTREAM_PACKAGE}:{UPSTREAM_VERSION}...", file=sys.stderr)
    returncode, griffe_output = run_griffe_check()
    print(griffe_output, file=sys.stderr)

    print(f"Loading fork API from {FORK_SOURCE_PATH}...", file=sys.stderr)
    fork = load_fork_api()

    report = generate_report(returncode, griffe_output, fork)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"\nReport written to {args.output}", file=sys.stderr)

    return 1 if (args.check and returncode != 0) else 0


if __name__ == "__main__":
    sys.exit(main())
