#!/usr/bin/env python3
"""
Generate a Markdown API compatibility report between the InquirerPrompt fork
and the upstream kazhala/InquirerPy package from PyPI.

Installs upstream InquirerPy into a temp directory and uses griffe.load() to
compare the two API surfaces — no griffe[pypi] extra or pypi: notation needed.

Usage:
    python scripts/compat_check.py [--output docs/pages/compat_report.md]

Requires:
    pip install griffe
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

try:
    import griffe
except ImportError:
    print("ERROR: griffe not installed. Run: pip install griffe", file=sys.stderr)
    sys.exit(1)


UPSTREAM_PACKAGE = "InquirerPy"
UPSTREAM_VERSION = "0.3.4"
FORK_SOURCE_PATH = Path(__file__).parent.parent  # repo root
OUTPUT_DEFAULT = Path(__file__).parent.parent / "docs" / "pages" / "compat_report.md"


def install_upstream(target: str) -> None:
    """Pip-install the upstream package into a target directory."""
    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            f"{UPSTREAM_PACKAGE}=={UPSTREAM_VERSION}",
            "--target",
            target,
            "--quiet",
            "--disable-pip-version-check",
        ],
        check=True,
        capture_output=False,
    )


def load_package(name: str, search_paths: list[str]) -> griffe.Package | None:
    try:
        return griffe.load(name, search_paths=search_paths)
    except Exception as e:
        print(f"WARNING: Could not load {name} from {search_paths}: {e}", file=sys.stderr)
        return None


def summarise_package(pkg: griffe.Package) -> dict[str, int]:
    counts: dict[str, int] = {"Classes": 0, "Functions": 0, "Attributes": 0}
    for obj in pkg.members.values():
        if isinstance(obj, griffe.Class):
            counts["Classes"] += 1
        elif isinstance(obj, griffe.Function):
            counts["Functions"] += 1
        else:
            counts["Attributes"] += 1
    return counts


def generate_report(
    breakages: list,
    upstream: griffe.Package | None,
    fork: griffe.Package | None,
) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        f"<!-- AUTO-GENERATED by scripts/compat_check.py on {now} — do not edit manually -->",
        "",
        f"*Report generated: {now}*",
        f"*Upstream reference: `{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}` (PyPI) — Fork: local `master`*",
        "",
    ]

    if not breakages:
        lines += [
            "## ✅ No Breaking Changes Detected",
            "",
            f"The public API of this fork is **fully compatible** with upstream "
            f"`{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}`.",
            "All existing code using the upstream package will continue to work without modification.",
            "",
        ]
    else:
        lines += [
            f"## ⚠️ {len(breakages)} API Difference(s) Found",
            "",
            "The following changes were detected relative to the upstream release.",
            "",
            "| Kind | Location | Description |",
            "|------|----------|-------------|",
        ]
        for b in breakages:
            kind = b.kind.value if hasattr(b.kind, "value") else str(b.kind)
            location = getattr(b, "obj_path", "unknown")
            description = str(b.explanation) if hasattr(b, "explanation") else ""
            lines.append(f"| `{kind}` | `{location}` | {description} |")
        lines.append("")

    # API surface comparison table
    if upstream is not None and fork is not None:
        up_counts = summarise_package(upstream)
        fork_counts = summarise_package(fork)
        lines += [
            "## API Surface Overview",
            "",
            "| Kind | Upstream | Fork | Delta |",
            "|------|----------|------|-------|",
        ]
        for kind in ("Classes", "Functions", "Attributes"):
            u = up_counts.get(kind, 0)
            f = fork_counts.get(kind, 0)
            delta = f"+{f - u}" if f > u else (str(f - u) if f < u else "=")
            lines.append(f"| {kind} | {u} | {f} | {delta} |")
        lines.append("")
    elif fork is not None:
        counts = summarise_package(fork)
        lines += [
            "## Fork API Surface (Top-Level)",
            "",
            "| Kind | Count |",
            "|------|-------|",
        ]
        for kind, n in counts.items():
            lines.append(f"| {kind} | {n} |")
        lines.append("")

    lines += ["---", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API compatibility report")
    parser.add_argument("--output", type=Path, default=OUTPUT_DEFAULT)
    parser.add_argument("--check", action="store_true", help="Exit 1 if breaking changes found")
    args = parser.parse_args()

    print(f"Installing upstream {UPSTREAM_PACKAGE}=={UPSTREAM_VERSION} to temp dir...", file=sys.stderr)
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            install_upstream(tmpdir)
        except subprocess.CalledProcessError as e:
            print(f"ERROR: pip install failed: {e}", file=sys.stderr)
            return 1

        print(f"Loading upstream from {tmpdir}...", file=sys.stderr)
        upstream = load_package(UPSTREAM_PACKAGE, [tmpdir])

        print(f"Loading fork from {FORK_SOURCE_PATH}...", file=sys.stderr)
        fork = load_package(UPSTREAM_PACKAGE, [str(FORK_SOURCE_PATH)])

        breakages: list = []
        if upstream is not None and fork is not None:
            print("Comparing API surfaces...", file=sys.stderr)
            try:
                breakages = list(griffe.find_breaking_changes(upstream, fork))
            except Exception as e:
                print(f"WARNING: find_breaking_changes failed: {e}", file=sys.stderr)

        report = generate_report(breakages, upstream, fork)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Report written to {args.output}", file=sys.stderr)

    if breakages:
        print(f"\n{len(breakages)} breaking change(s) found:", file=sys.stderr)
        for b in breakages:
            print(f"  - {b}", file=sys.stderr)
    else:
        print("\nNo breaking changes found.", file=sys.stderr)

    return 1 if (args.check and breakages) else 0


if __name__ == "__main__":
    sys.exit(main())
