#!/usr/bin/env python3
"""
Generate a Markdown API compatibility report between the InquirerPrompt fork
and the upstream kazhala/InquirerPy package from PyPI.

Usage:
    python scripts/compat_check.py [--output docs/pages/compat_report.md]

Requires:
    pip install griffe[pypi]
"""
from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

try:
    import griffe
except ImportError:
    print("ERROR: griffe not installed. Run: pip install griffe[pypi]", file=sys.stderr)
    sys.exit(1)


UPSTREAM_PACKAGE = "InquirerPy"
UPSTREAM_VERSION = "0.3.4"
FORK_SOURCE_PATH = Path(__file__).parent.parent  # repo root
OUTPUT_DEFAULT = Path(__file__).parent.parent / "docs" / "pages" / "compat_report.md"


def load_upstream() -> griffe.Package:
    """Load upstream InquirerPy from PyPI."""
    try:
        return griffe.load_pypi(UPSTREAM_PACKAGE, UPSTREAM_VERSION)
    except Exception as e:
        print(f"WARNING: Could not load from PyPI ({e}). Trying git tags...", file=sys.stderr)
        # Fallback: load from git tag in upstream if cloned — generally won't be available
        raise


def load_fork() -> griffe.Package:
    """Load InquirerPy from the current fork source tree."""
    return griffe.load(UPSTREAM_PACKAGE, search_paths=[str(FORK_SOURCE_PATH)])


def severity_icon(kind: str) -> str:
    icons = {
        "attribute-removed": "❌",
        "class-removed": "❌",
        "function-removed": "❌",
        "object-removed": "❌",
        "parameter-removed": "⚠️",
        "parameter-moved": "⚠️",
        "parameter-changed-kind": "⚠️",
        "parameter-changed-default": "ℹ️",
        "parameter-added-required": "⚠️",
        "return-changed-annotation": "ℹ️",
        "attribute-changed-value": "ℹ️",
    }
    return icons.get(kind, "⚠️")


def generate_report(breakages: list, upstream: griffe.Package, fork: griffe.Package) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = [
        f"<!-- AUTO-GENERATED by scripts/compat_check.py on {now} — do not edit manually -->",
        "",
        f"*Report generated: {now}*",
        f"*Upstream: `{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}` (PyPI) — Fork: `master`*",
        "",
    ]

    if not breakages:
        lines += [
            "## ✅ No Breaking Changes Detected",
            "",
            f"The public API of this fork is **fully compatible** with upstream `{UPSTREAM_PACKAGE} {UPSTREAM_VERSION}`.",
            "All existing code using the upstream package will continue to work without modification.",
            "",
        ]
    else:
        lines += [
            f"## ⚠️ {len(breakages)} API Difference(s) Found",
            "",
            "The following changes were detected relative to the upstream release.",
            "Items marked ❌ are **breaking changes**. Items marked ⚠️ are **potentially breaking**.",
            "",
            "| Icon | Kind | Location | Description |",
            "|------|------|----------|-------------|",
        ]
        for b in breakages:
            icon = severity_icon(b.kind.value if hasattr(b.kind, "value") else str(b.kind))
            kind = b.kind.value if hasattr(b.kind, "value") else str(b.kind)
            location = getattr(b, "obj_path", getattr(b, "breakage_path", "unknown"))
            description = str(b.explanation) if hasattr(b, "explanation") else ""
            lines.append(f"| {icon} | `{kind}` | `{location}` | {description} |")
        lines.append("")

    # API surface summary
    def count_members(pkg: griffe.Package) -> dict[str, int]:
        counts: dict[str, int] = {"functions": 0, "classes": 0, "attributes": 0}
        for obj in pkg.members.values():
            if isinstance(obj, griffe.Function):
                counts["functions"] += 1
            elif isinstance(obj, griffe.Class):
                counts["classes"] += 1
            else:
                counts["attributes"] += 1
        return counts

    lines += [
        "## API Surface Overview",
        "",
        "| | Upstream | Fork |",
        "|-|----------|------|",
    ]

    try:
        up_counts = count_members(upstream)
        fork_counts = count_members(fork)
        for key in ("classes", "functions", "attributes"):
            u = up_counts.get(key, 0)
            f = fork_counts.get(key, 0)
            delta = f"(+{f - u})" if f > u else (f"({f - u})" if f < u else "(=)")
            lines.append(f"| {key.capitalize()} | {u} | {f} {delta} |")
    except Exception as e:
        lines.append(f"| (error counting members) | — | {e} |")

    lines += ["", "---", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API compatibility report")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_DEFAULT,
        help="Output markdown file path",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with code 1 if breaking changes are found",
    )
    args = parser.parse_args()

    print(f"Loading upstream {UPSTREAM_PACKAGE} {UPSTREAM_VERSION} from PyPI...", file=sys.stderr)
    try:
        upstream = load_upstream()
    except Exception as e:
        print(f"ERROR loading upstream: {e}", file=sys.stderr)
        return 1

    print(f"Loading fork from {FORK_SOURCE_PATH}...", file=sys.stderr)
    fork = load_fork()

    print("Checking for breaking changes...", file=sys.stderr)
    breakages = list(griffe.find_breaking_changes(upstream, fork))

    report = generate_report(breakages, upstream, fork)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Report written to {args.output}", file=sys.stderr)

    if breakages:
        print(f"\n{len(breakages)} breaking change(s) found:", file=sys.stderr)
        for b in breakages:
            print(f"  - {b}", file=sys.stderr)

    return 1 if (args.check and breakages) else 0


if __name__ == "__main__":
    sys.exit(main())
